<?php
/**
 * Uninstall Future MD plugin.
 *
 * @author Terry Lin
 * @link https://terryl.in/future
 *
 * @package Future
 * @since 1.0.0
 * @version 1.7.5
 */

// if uninstall.php is not called by WordPress, die.
if ( ! defined( 'WP_UNINSTALL_PLUGIN' ) ) {
	die;
}

if ( ! function_exists( 'future_get_option' ) ) {
	function future_get_option( $option, $section, $default = '' ) {
		$options = get_option( $section );
	
		if ( isset( $options[ $option ] ) ) {
			return $options[ $option ];
		}
		return $default;
	}
}

if ( 'yes' === future_get_option( 'clear_all_settings', 'future_preferences' ) ) {
 
	$options_names = array(
		'future_markdown',
		'future_modules',
		'future_extensions',
		'future_preferences',
	);

	foreach ( $options_names as $option_name ) {
		delete_option( $option_name );
		delete_site_option( $option_name );
	}

	delete_option( 'future_migration_v162' );

	$post_meta_keys = array(
		'_is_future_markdown',
		'_future_prismjs',
		'_is_future_sequence',
		'_is_future_flow_chart',
		'_is_future_katex',
	);

	// Remove all post_meta generated by Future MD.
	foreach ( $post_meta_keys as $meta_key ) {
		delete_post_meta_by_key( $meta_key );
	}
}

// enable rich text.
add_filter( 'user_can_richedit', '__return_true' );

// drop a custom database table
// global $wpdb;
//$wpdb->query("DROP TABLE IF EXISTS {$wpdb->prefix}mytable");